name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [18, 20, 22]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Formatting, Linting, Types
        run: npm run check

      - name: Run Tests
        run: npm run test
